name: Daily AI News Email

on:
  schedule:
    - cron: "30 7 * * *"  # Every day at 07:30 GMT (08:30 BST)
  workflow_dispatch:  # Allow manual runs

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Add timeout to prevent hanging
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Download NLTK data
        run: |
          python -c "import nltk; nltk.download('punkt')"
          
      - name: Run script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: python main.py